name: Run Main Program and Microservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]    # Node.js version
        python-version: ["3.10"]  # Python version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install Node dependencies for MainProg
      - name: Install Node dependencies for MainProg
        run: npm install || echo "No dependencies to install"

      # Install Node dependencies for Microservices B, C, D
      - name: Install Node dependencies for Microservices
        run: |
          for dir in microserviceB microserviceC microserviceD; do
            if [ -f "$dir/package.json" ]; then
              cd $dir
              npm install
              cd ..
            else
              echo "No package.json in $dir, skipping npm install"
            fi
          done

      # Install nodemon globally
      - name: Install nodemon globally
        run: npm install -g nodemon

      # Install Python dependencies for MicroserviceA
      - name: Install Python dependencies for MicroserviceA
        run: |
          python -m pip install --upgrade pip
          if [ -f microserviceA/requirements.txt ]; then
            pip install -r microserviceA/requirements.txt
          else
            echo "No requirements.txt found, skipping Python dependencies"
          fi

      # Run all microservices and Main Program concurrently
      - name: Start Microservices and Main Program
        run: |
          echo "Starting MicroserviceA..."
          cd microserviceA && nohup python microserviceA.py & cd ..
          
          echo "Starting MicroserviceB..."
          cd microserviceB && nohup node microserviceB.js & cd ..
          
          echo "Starting MicroserviceC..."
          cd microserviceC && nohup node microserviceC.js & cd ..
          
          echo "Starting MicroserviceD..."
          cd microserviceD && nohup node microserviceD.js & cd ..
          
          echo "Starting Main Program..."
          nohup nodemon server.js &

          wait
