name: Run Main Program and Microservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]   # adjust Node.js version
        python-version: [3.10] # adjust Python version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Install Node dependencies for MainProg
      - name: Install Node dependencies for MainProg
        run: npm install

      # Optional: Install nodemon globally if not in package.json
      - name: Install nodemon globally
        run: npm install -g nodemon

      # Install Python dependencies for MicroserviceA
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r microserviceA/requirements.txt

      # Run MicroserviceA
      - name: Start MicroserviceA
        run: |
          cd microserviceA
          nohup python microserviceA.py &

      # Run MicroserviceB
      - name: Start MicroserviceB
        run: |
          cd microserviceB
          nohup node microserviceB.js &

      # Run MicroserviceC
      - name: Start MicroserviceC
        run: |
          cd microserviceC
          nohup node microserviceC.js &

      # Run MicroserviceD
      - name: Start MicroserviceD
        run: |
          cd microserviceD
          nohup node microserviceD.js &

      # Run Main Program
      - name: Start Main Program
        run: |
          nohup nodemon server.js &
